### ISSUE TITLE
Apk install hangs forever

### ISSUE THREAD

**Issue by vsatmydynipnet** [lapulpeta/Nostrid#114]
Trying to install on rooted LineageOS 19  (Android 12), no gapps, firewalled by afwall+, so no Internet during install, using Shelter from F-Droid and  - Install apk into Work Profile - hangs forever.

**Comment by vsatmydynipnet** [comment]
Interesting this Install display lays over the cancel/install question. Saw that on the tablet.
![Screenshot_20230305-114131_Paketinstallation](https://user-images.githubusercontent.com/18069867/222955591-d1b99cdb-67a4-41bc-86df-457b8ee936a7.png)
Got it intalled on the tablet while rotating it a few times and fast touching.

**Comment by lapulpeta** [comment]
Isn't all this happening *before* Nostrid is installed? Are you sure this is only happening with Nostrid and not with all APKs?

**Comment by vsatmydynipnet** [comment]
Sorry, my fault. There must be a shelter problem, its laying over it also with others. Got Nostrid run now on phone and tablet with rotating and fast touch.
