### ISSUE TITLE
Version 1.6 apk don't start

### ISSUE THREAD

**Issue by grunch** [lapulpeta/Nostrid#32]
After update to v1.6 I can't use nostrid

Google pixel 6a
Android 13

![Screenshot_20230117-094356.png](https://user-images.githubusercontent.com/228364/212902116-3844e69a-2201-4693-8803-c73770f1a3e9.png)

**Comment by lapulpeta** [comment]
Try clearing the app data, or uninstalling and installing it again.

**Comment by grunch** [comment]
I did all that, still can't use it

**Comment by lapulpeta** [comment]
Does v1.5 work in your device?

**Comment by grunch** [comment]
I never installed it, before 1.6 I had installed 1.3, Let me try 1.5

**Comment by lapulpeta** [comment]
What about v1.4?

**Comment by grunch** [comment]
v1.4 don't work neither, I just installed 1.3 again and it works

**Comment by lapulpeta** [comment]
Ok I'll see if I can reproduce the error in a simulator

**Comment by lapulpeta** [comment]
I didn't find an image for Pixel 6a, but I tried it in Pixel 5 Android 13 and Nexus 6P Android 13 and they both work fine.

Can you try these builds? They are intermediate points between 1.3 and 1.4, let's see if we can pin point the exact commit that causes the error. Let me know which one works (if any).

https://github.com/lapulpeta/Nostrid-media/raw/main/com.nostrid.nostrid-034a83a1.apk
https://github.com/lapulpeta/Nostrid-media/raw/main/com.nostrid.nostrid-2a036ea8.apk
https://github.com/lapulpeta/Nostrid-media/raw/main/com.nostrid.nostrid-dca6807c.apk

**Comment by lapulpeta** [comment]
Make sure you try all the builds (they are not in order)

**Comment by grunch** [comment]
I installed all of them, I got the same result

**Comment by grunch** [comment]
The issue continues with v1.7, maybe you can add some way of export some related output on the crash

**Comment by lapulpeta** [comment]
Can you try this one?

https://github.com/lapulpeta/Nostrid-media/raw/main/com.nostrid.nostrid-9fde558.apk

**Comment by grunch** [comment]
that one works

> Can you try this one?
> 
> https://github.com/lapulpeta/Nostrid-media/raw/main/com.nostrid.nostrid-9fde558.apk

**Comment by lapulpeta** [comment]
Ok, I know which commit is causing it to fail, but I don't know why. I assume v1.8 is not working for you? Also can you try v1.2?

**Comment by grunch** [comment]
v1.8 don't work, v1.2 works, all versions until v1.3 works

**Comment by lapulpeta** [comment]
We changed the database engine in v1.11. Can you please give it a try?

**Comment by grunch** [comment]
It works! thank you for this wonderful work
