### ISSUE TITLE
[Functional request] Add proxy support

### ISSUE THREAD

**Issue by chenshaoju** [lapulpeta/Nostrid#70]
Sorry for my English.

In some cases, users need a proxy to access the internet, or behind the [national firewall](https://en.wikipedia.org/wiki/Great_Firewall), 

I hope we can add proxy support.

Thank you.

**Comment by lapulpeta** [comment]
We will consider this. Thanks.

**Comment by lapulpeta** [comment]
v1.19 has proxy support. Let me know if it works for you.

**Comment by chenshaoju** [comment]
After using [AppContainer Loopback Exemption Utility](https://docs.telerik.com/fiddler/configure-fiddler/tasks/configurefiddlerforwin8) add Nostrid to exception, local [Shadowsocks](https://github.com/shadowsocks/) proxy is working fine now.

Thank you so much!

![Snipaste_2023-02-09_10-41-25](https://user-images.githubusercontent.com/515763/217703924-623b6b0a-f724-4fd1-a495-2f6705773123.png)

**Comment by lapulpeta** [comment]
Glad to hear it works!
