### ISSUE TITLE
Trying to run up in Visual Studio

### ISSUE THREAD

**Issue by mjlamb** [lapulpeta/Nostrid#80]
Hi, having truble getting the project running.
Visual Studio
- Set as Startup -> Nostrid.Web
- Debug, Run
I get an "An unhandled error has occurred. [Reload](https://localhost:7071/)" in the UI

EventDatabase.cs line 26
if (db.Database.SqlQuery<bool>($"SELECT 1 AS [Value] FROM sqlite_master WHERE type='table' AND name='__EFMigrationsHistory'").FirstOrDefault())

Any ideas, seems to have trouble setup of database?

**Comment by mjlamb** [comment]
Either, I do not mind, just trying to get any of it running at this stage. Ta

**Comment by lapulpeta** [comment]
To run the desktop app you need to start the `Nostrid` project (not `Nostrid.Web` or `Nostrid.Core`). Let me know if it works.

**Comment by mjlamb** [comment]
Ok just making some notes.
Set the startup project to "Nostrid"
Solution didn't build, told me to run "dotnet workload restore"
Run dotnet workload restore
- Successfully installed workload(s) maui-android maui-ios maui-maccatalyst maui-tizen.

Build solution = still failed

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1147	To build this project, the following workloads must be installed: maui-mobile
To install these workloads, run the following command: dotnet workload restore	Nostrid	C:\Program Files\dotnet\sdk\7.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	

Already done the above, doesn't build.

**Comment by lapulpeta** [comment]
Are you using Visual Studio 2022? Did you enable `.NET Multi-platform App UI development` during installation? If not then you can run the installer again and then choose `Modify`.

**Comment by mjlamb** [comment]
Installed that now. Thanks

Build Solution = 


Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\_MyData\Nostrid\Nostrid\obj\project.assets.json' doesn't have a target for 'net7.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net7.0-windows10.0.19041.0' in the TargetFrameworks for your project.	Nostrid	C:\Program Files\dotnet\sdk\7.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\_MyData\Nostrid\Nostrid\obj\project.assets.json' doesn't have a target for 'net7.0-android'. Ensure that restore has run and that you have included 'net7.0-android' in the TargetFrameworks for your project.	Nostrid	C:\Program Files\dotnet\sdk\7.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\_MyData\Nostrid\Nostrid\obj\project.assets.json' doesn't have a target for 'net7.0-maccatalyst'. Ensure that restore has run and that you have included 'net7.0-maccatalyst' in the TargetFrameworks for your project.	Nostrid	C:\Program Files\dotnet\sdk\7.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\_MyData\Nostrid\Nostrid\obj\project.assets.json' doesn't have a target for 'net7.0-ios'. Ensure that restore has run and that you have included 'net7.0-ios' in the TargetFrameworks for your project.	Nostrid	C:\Program Files\dotnet\sdk\7.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	


Ran dotnet restore.
Still same error above, won't build

**Comment by mjlamb** [comment]
Got it running. Had to turn on developer mode in windows. The nostrid ui is up and working now.

**Comment by mjlamb** [comment]
Were is the sqllite db created on disk ?

**Comment by lapulpeta** [comment]
Glad to hear it works.
The database should be in a directory similar to this one: `C:\Users\{username}\AppData\Local\Packages\54CE2B71...\LocalState`
